import React from 'react';
import { SiteData } from '../../types';

interface SimplePreviewTemplateProps {
  siteData: SiteData;
}

export const SimplePreviewTemplate: React.FC<SimplePreviewTemplateProps> = ({ siteData }) => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-indigo-900">
      {/* Header */}
      <header className="bg-black/20 backdrop-blur-lg border-b border-white/10">
        <div className="max-w-6xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold text-white">{siteData.title}</h1>
            <div className="flex gap-4">
              <button className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
                Star ⭐
              </button>
              <button className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors">
                Fork 🍴
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto text-center">
          <h2 className="text-5xl font-bold text-white mb-6">
            {siteData.title}
          </h2>
          <p className="text-xl text-blue-200 mb-8 max-w-3xl mx-auto">
            {siteData.description}
          </p>
          
          {/* Tech Stack */}
          {siteData.techStack && siteData.techStack.length > 0 && (
            <div className="flex flex-wrap justify-center gap-3 mb-8">
              {siteData.techStack.map((tech, index) => (
                <span 
                  key={index}
                  className="px-3 py-1 bg-blue-600/30 text-blue-200 rounded-full text-sm border border-blue-400/30"
                >
                  {tech}
                </span>
              ))}
            </div>
          )}

          <div className="flex gap-4 justify-center">
            <button className="px-8 py-3 bg-gradient-to-r from-blue-500 to-purple-600 text-white font-semibold rounded-lg hover:shadow-lg transition-all">
              Get Started
            </button>
            <button className="px-8 py-3 bg-white/10 text-white font-semibold rounded-lg border border-white/20 hover:bg-white/20 transition-all">
              View on GitHub
            </button>
          </div>
        </div>
      </section>

      {/* Features */}
      {siteData.features && siteData.features.length > 0 && (
        <section className="py-16 px-6">
          <div className="max-w-6xl mx-auto">
            <h3 className="text-3xl font-bold text-white text-center mb-12">Key Features</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {siteData.features.map((feature, index) => (
                <div 
                  key={index}
                  className="p-6 bg-white/5 backdrop-blur-lg rounded-xl border border-white/10 hover:bg-white/10 transition-all"
                >
                  <div className="text-4xl mb-4">⚡</div>
                  <h4 className="text-lg font-semibold text-white mb-2">{feature}</h4>
                  <p className="text-blue-200">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Sections */}
      {siteData.sections && siteData.sections.length > 0 && (
        <section className="py-16 px-6">
          <div className="max-w-4xl mx-auto">
            {siteData.sections.map((section, index) => (
              <div key={index} className="mb-12">
                <div className="p-8 bg-white/5 backdrop-blur-lg rounded-xl border border-white/10">
                  <h3 className="text-2xl font-bold text-white mb-4">{section.title}</h3>
                  <div 
                    className="text-blue-200 prose prose-lg max-w-none"
                    dangerouslySetInnerHTML={{ __html: section.content }}
                  />
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Footer */}
      <footer className="bg-black/30 backdrop-blur-lg border-t border-white/10 py-8">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <p className="text-blue-200">
            Generated by <span className="font-semibold text-white">4site.pro</span> • 
            Deploy to GitHub Pages in seconds
          </p>
        </div>
      </footer>
    </div>
  );
};